services:

  postgres:
    image: postgres:17

    container_name: user-service-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password

    ports:
      - "5432:5432"

    volumes:
      - user_postgres_data:/var/lib/postgresql/data


volumes:
  user_postgres_data: